document.writeln("<div id=\"bottom\">");
document.writeln("		<div id=\"bottom_center\">");
document.writeln("		<ul><li><a href=\"#\"><span>友情链接：</span>百度</a></li>");
document.writeln("		<li><a href=\"#\">Google</a></li>");
document.writeln("		<li><a href=\"#\">雅虎</a></li>");
document.writeln("		<li><a href=\"#\">淘宝</a></li>");
document.writeln("		<li><a href=\"#\">拍拍</a></li>");
document.writeln("		<li><a href=\"#\">易趣</a></li>");
document.writeln("		<li><a href=\"#\">当当</a></li>");
document.writeln("		<li><a href=\"#\">京东商城</a></li>");
document.writeln("		<li><a href=\"#\">迅雷</a></li>");
document.writeln("		<li><a href=\"#\">新浪</a></li>");
document.writeln("		<li><a href=\"#\">网易</a></li>");
document.writeln("		<li><a href=\"#\">搜狐</a></li>");
document.writeln("		<li><a href=\"#\">猫扑</a></li>");
document.writeln("		<li><a href=\"#\">开心网</a></li>");
document.writeln("		<li><a href=\"#\">新华网</a></li>");
document.writeln("		<li id = \"lastli\"><a href=\"#\">凤凰网</a></li>");
document.writeln("		</ul>");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		<p id=\"clearFloat\">COPYRIGHT &copy;2003-2010北京市贵美商城有限公司 ALL RIGHT RESERVED</p>");
document.writeln("		<p><span>热线：</span>400-66-13060 Email:service@prd.com</p>");
document.writeln("		<p><span>ICP:</span>沪ICP备05021104号</p>");
document.writeln("		<p>");
document.writeln("			<image src=\"./images/img1.gif\"></image>");
document.writeln("			<image src=\"./images/img2.gif\"></image>");
document.writeln("			<image src=\"./images/img3.gif\"></image>");
document.writeln("			<image src=\"./images/img4.gif\"></image>");
document.writeln("		</p>");
document.writeln("	</div>");