document.writeln("<div id=\'nav\' >");
document.writeln("		<div id=\'nav_top\'>");
document.writeln("			<ul >");
document.writeln("				<li class=\'toplist\' ><div id=\'icon1\'></div><p><a href=\'cart.html\'>购物车</a></p></li>");
document.writeln("				<li class=\'toplist\' ><div id=\'icon2\'></div><p><a href=\'help1.html\'>帮助中心</a></p></li>");
document.writeln("				<li class=\'toplist\' ><div id=\'icon3\'></div><p><a href=\'#\'>加入收藏</a></p></li>");
document.writeln("				<li class=\'toplist\' ><div id=\'icon4\'></div><p><a href=\'#\'>设为首页</a></p></li>");
document.writeln("				<li class=\'toplist\' ><div ></div><a href=\'login.html\' id=\'icon5\'>登录</a></li>");
document.writeln("				<li class=\'toplist\' ><div ></div><a href=\'register.html\' id=\'icon6\'>注册</a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("		<div id=\'nav_bot\'>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'index.html\'>首页</a></li>");
document.writeln("				<li><a href=\'goods_list.html\'>家用电器</a></li>");
document.writeln("				<li><a href=\'detail.html\'>手机数码</a></li>");
document.writeln("				<li><a href=\'#\'>日用百货</a></li>");
document.writeln("				<li><a href=\'#\'>书籍</a></li>");
document.writeln("				<li><a href=\'help1.html\'>帮助中心</a></li>");
document.writeln("				<li><a href=\'#\'>免费开店</a></li>");
document.writeln("				<li><a href=\'#\'>全球咨询</a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");